
services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001" # Порт для MinIO Console
    environment:
      MINIO_ROOT_USER:  ruhani
      MINIO_ROOT_PASSWORD: Q!122WS@ws))-=+32
    volumes:
      - /Users/xakus/Documents/projeects/S3Minio/docker_file/data:/data
    command: server /data --console-address ":9001"
